//
// VIN. (C) 2016-2023 Dr. Michael 'Mickey' Lauer <mickey@Vanille.de>
//

/// Directory of World Manufacturer Identifiers (WMI, VIN positions 1–3, or the
/// 2-character prefix for small-volume makers) mapped to manufacturer names.
///
/// Manufacturer names are proper nouns and intentionally not localized.
/// Lookup tries the full 3-character WMI first, then the 2-character prefix.
let vinManufacturers: [String: String] = [
    "19U": "Acura", "19X": "Honda", "1B3": "Dodge",
    "1B4": "Dodge", "1B7": "Dodge", "1C3": "Chrysler",
    "1C4": "Chrysler", "1C6": "Ram", "1C8": "Chrysler",
    "1D3": "Dodge", "1D4": "Dodge", "1D7": "Dodge",
    "1F9": "FWD Corp.", "1FA": "Ford", "1FB": "Ford",
    "1FC": "Ford", "1FD": "Ford", "1FM": "Ford",
    "1FT": "Ford", "1FU": "Freightliner", "1FV": "Freightliner",
    "1G0": "GMC", "1G1": "Chevrolet", "1G2": "Pontiac",
    "1G3": "Oldsmobile", "1G4": "Buick", "1G6": "Cadillac",
    "1G8": "Saturn USA", "1GB": "Chevrolet", "1GC": "Chevrolet",
    "1GM": "Pontiac", "1GN": "Chevrolet SUV USA", "1GT": "GMC",
    "1GY": "Cadillac", "1HD": "Harley-Davidson", "1HG": "Honda",
    "1HT": "International Truck and Engine Corp. USA", "1J4": "Jeep", "1J8": "Jeep",
    "1LN": "Lincoln", "1M1": "Mack Truck USA", "1M2": "Mack Truck USA",
    "1M3": "Mack Truck USA", "1M4": "Mack Truck USA", "1M9": "Mynatt Truck & Equipment",
    "1ME": "Mercury", "1N4": "Nissan", "1N6": "Nissan",
    "1NX": "NUMMI USA", "1P3": "Plymouth USA", "1PY": "John Deere USA",
    "1R9": "Roadrunner Hay Squeeze USA", "1VW": "Volkswagen", "1XK": "Kenworth USA",
    "1XP": "Peterbilt USA", "1YV": "Mazda", "1ZV": "Ford (AutoAlliance International)",
    "2A4": "Chrysler Canada", "2B3": "Dodge Canada", "2B7": "Dodge Canada",
    "2BP": "Bombardier Recreational Products", "2C3": "Chrysler Canada", "2CN": "CAMI",
    "2D3": "Dodge Canada", "2FA": "Ford Motor Company Canada", "2FB": "Ford Motor Company Canada",
    "2FC": "Ford Motor Company Canada", "2FM": "Ford Motor Company Canada", "2FT": "Ford Motor Company Canada",
    "2FU": "Freightliner", "2FV": "Freightliner", "2FZ": "Sterling",
    "2G1": "Chevrolet", "2G2": "Pontiac Canada", "2G3": "Oldsmobile Canada",
    "2G4": "Buick Canada", "2G9": "mfr. of less than 1000/ yr. Canada", "2HG": "Honda",
    "2HJ": "Honda Canada", "2HK": "Honda", "2HM": "Hyundai Canada",
    "2NV": "Nova Bus Canada", "2P3": "Plymouth Canada", "2T1": "Toyota",
    "2T2": "Lexus", "2TP": "Triple E Canada LTD", "2V4": "Volkswagen Canada",
    "2V8": "Volkswagen Canada", "2WK": "Western Star", "2WL": "Western Star",
    "2WM": "Western Star", "363": "Spyker", "3C4": "Chrysler Mexico",
    "3C6": "RAM Mexico", "3D3": "Dodge Mexico", "3D4": "Dodge Mexico",
    "3FA": "Ford", "3FE": "Ford Motor Company Mexico", "3GC": "Chevrolet",
    "3JB": "BRP Mexico (all-terrain vehicles)", "3MD": "Mazda Mexico", "3MZ": "Mazda",
    "3N1": "Nissan", "3NE": "Polaris Industries USA", "3NS": "Polaris Industries USA",
    // FCA / Chrysler family WMIs reported by NHTSA vPIC.
    "1A2": "FCA US", "1A3": "FCA US", "1A4": "FCA US",
    "1A6": "FCA US", "1A7": "FCA US", "1A8": "FCA US",
    "1B2": "FCA US", "1B5": "FCA US", "1B6": "FCA US",
    "1B8": "FCA US", "1C2": "FCA US", "1C5": "FCA US",
    "1C7": "FCA US", "1D2": "FCA US", "1D5": "FCA US",
    "1D6": "FCA US", "1D8": "FCA US", "1E3": "FCA US",
    "1J2": "FCA US", "1J3": "FCA US", "1J5": "FCA US",
    "1J6": "FCA US", "1J7": "FCA US", "1JC": "FCA US",
    "1JD": "FCA US", "1JT": "FCA US", "1P4": "FCA US",
    "1P5": "FCA US", "1P6": "FCA US", "1P7": "FCA US",
    "1VH": "DaimlerChrysler Commercial Buses", "1XM": "FCA US", "1Z2": "FCA US",
    "1Z3": "FCA US", "1Z4": "FCA US", "1Z6": "FCA US",
    "1Z7": "FCA US", "1Z8": "FCA US", "2A2": "FCA Canada",
    "2A3": "FCA Canada", "2A6": "FCA Canada", "2A7": "FCA Canada",
    "2A8": "FCA Canada", "2B1": "DaimlerChrysler Commercial Buses Canada", "2B2": "FCA Canada",
    "2B4": "FCA Canada", "2B5": "FCA Canada", "2B6": "FCA Canada",
    "2B8": "FCA Canada", "2BA": "DaimlerChrysler Commercial Buses Canada", "2C4": "FCA Canada",
    "2C5": "FCA Canada", "2C6": "FCA Canada", "2C7": "FCA Canada",
    "2C8": "FCA Canada", "2CA": "FCA Canada", "2D2": "FCA Canada",
    "2D4": "FCA Canada", "2D5": "FCA Canada", "2D6": "FCA Canada",
    "2D7": "FCA Canada", "2D8": "FCA Canada", "2E3": "FCA Canada",
    "2E4": "FCA Canada", "2J4": "FCA Canada", "2J5": "FCA Canada",
    "2J6": "FCA Canada", "2P4": "FCA Canada", "2P5": "FCA Canada",
    "2P6": "FCA Canada", "2P7": "FCA Canada", "2XM": "Chrysler",
    "3A2": "Chrysler Mexico", "3A3": "Chrysler Mexico", "3A4": "Chrysler Mexico",
    "3A6": "Chrysler Mexico", "3A7": "Chrysler Mexico", "3A8": "Chrysler Mexico",
    "3B2": "Chrysler Mexico", "3B3": "Chrysler Mexico", "3B4": "Chrysler Mexico",
    "3B5": "Chrysler Mexico", "3B6": "Chrysler Mexico", "3B7": "Chrysler Mexico",
    "3B8": "Chrysler Mexico", "3C2": "Chrysler Mexico", "3C3": "Chrysler Mexico",
    "3C5": "Chrysler Mexico", "3C7": "Chrysler Mexico", "3C8": "Chrysler Mexico",
    "3CA": "Chrysler Mexico", "3D2": "Chrysler Mexico", "3D5": "Chrysler Mexico",
    "3D6": "Chrysler Mexico", "3D7": "Chrysler Mexico", "3D8": "Chrysler Mexico",
    "3E3": "Chrysler Mexico", "3E4": "Chrysler Mexico", "3F6": "Chrysler Mexico",
    "3J4": "Chrysler Mexico", "3J5": "Chrysler Mexico", "3J6": "Chrysler Mexico",
    "3P4": "Chrysler Mexico", "3P5": "Chrysler Mexico", "3P6": "Chrysler Mexico",
    "3P7": "Chrysler Mexico", "4B3": "FCA US", "4C3": "FCA US",
    "4E3": "FCA US", "JB3": "FCA US", "JE3": "FCA US",
    "MN3": "FCA US", "WCD": "DaimlerChrysler", "WD1": "DaimlerChrysler",
    "WD2": "DaimlerChrysler", "WD5": "DaimlerChrysler", "WD6": "DaimlerChrysler",
    "WD7": "DaimlerChrysler", "WDP": "DaimlerChrysler", "WDR": "DaimlerChrysler",
    "WDY": "DaimlerChrysler", "ZAC": "FCA Italy",
    "3P3": "Plymouth Mexico", "3VW": "Volkswagen", "46J": "Federal Motors Inc. USA",
    "4EN": "Emergency One USA", "4JG": "Mercedes-Benz", "4P1": "Pierce Manufacturing Inc. USA",
    "4RK": "Nova Bus USA", "4T1": "Toyota", "4T3": "Toyota",
    "4T9": "Lumen Motors", "4UF": "Arctic Cat Inc.", "4US": "BMW",
    "4UZ": "Frt-Thomas Bus", "4V1": "Volvo", "4V2": "Volvo",
    "4V3": "Volvo", "4V4": "Volvo", "4V5": "Volvo",
    "4V6": "Volvo", "4VL": "Volvo", "4VM": "Volvo",
    "4VZ": "Volvo", "538": "Zero Motorcycles (USA)", "56K": "Indian Motorcycle USA",
    "58A": "Toyota USA - Kentucky (Lexus ES)", "5FN": "Honda", "5J6": "Honda",
    "5N1": "Nissan USA", "5NP": "Hyundai USA", "5TD": "Toyota",
    "5TF": "Toyota", "5UX": "BMW", "5YJ": "Tesla",
    "5YM": "BMW", "6AB": "MAN Australia", "6F4": "Nissan Motor Company Australia",
    "6F5": "Kenworth Australia", "6FP": "Ford Motor Company Australia", "6G1": "General Motors-Holden (post Nov 2002)",
    "6G2": "Pontiac Australia (GTO & G8)", "6H8": "General Motors-Holden (pre Nov 2002)", "6MM": "Mitsubishi Motors Australia",
    "6T1": "Toyota Motor Corporation Australia", "6U9": "Privately Imported car in Australia", "795": "Bugatti",
    "7SA": "Tesla", "8A1": "Renault Argentina", "8AD": "Peugeot Argentina",
    "8AF": "Ford Motor Company Argentina", "8AG": "Chevrolet Argentina", "8AJ": "Toyota Argentina",
    "8AK": "Suzuki Argentina", "8AP": "Fiat Argentina", "8AW": "Volkswagen Argentina",
    "8GD": "Peugeot Chile", "8GG": "Chevrolet Chile", "8LD": "Chevrolet Ecuador",
    "92H": "Origem Brazil", "935": "Citroën Brazil", "936": "Peugeot Brazil",
    "93H": "Honda Brazil", "93R": "Toyota Brazil", "93U": "Audi Brazil",
    "93V": "Audi Brazil", "93X": "Mitsubishi Motors Brazil", "93Y": "Renault Brazil",
    "94D": "Nissan Brazil", "9BD": "Fiat Brazil", "9BF": "Ford Motor Company Brazil",
    "9BG": "Chevrolet Brazil", "9BM": "Mercedes-Benz Brazil", "9BR": "Toyota Brazil",
    "9BS": "Scania Brazil", "9BW": "Volkswagen", "9FB": "Renault Colombia",
    "9GA": "Chevrolet Colombia", "AAV": "Volkswagen South Africa", "AC5": "Hyundai South Africa",
    "ADD": "Hyundai South Africa", "AFA": "Ford South Africa", "AHT": "Toyota South Africa",
    "BR1": "Mercedes-Benz Algeria (SAFAV MB)", "EAA": "Aurus", "HAC": "GAC",
    "HLX": "Li Auto", "HXM": "Xiaomi", "JA3": "Mitsubishi",
    "JA4": "Mitsubishi", "JAA": "Isuzu", "JAM": "Isuzu",
    "JDA": "Daihatsu", "JF1": "Subaru", "JH1": "Honda",
    "JH2": "Honda", "JH3": "Honda", "JH4": "Acura",
    "JH5": "Honda", "JHA": "Hino", "JHB": "Hino",
    "JHC": "Hino", "JHD": "Hino", "JHE": "Hino",
    "JHF": "Honda", "JHG": "Honda", "JHH": "Hino",
    "JHI": "Hino", "JHJ": "Hino", "JHK": "Hino",
    "JHL": "Honda", "JHM": "Honda", "JHN": "Honda",
    "JHO": "Hino", "JHZ": "Honda", "JKA": "Kawasaki",
    "JL5": "Mitsubishi Fuso", "JM1": "Mazda", "JMA": "Mitsubishi",
    "JMB": "Mitsubishi Motors", "JMY": "Mitsubishi Motors", "JMZ": "Mazda",
    "JN1": "Nissan", "JNK": "Infiniti", "JS1": "Suzuki",
    "JS2": "Suzuki", "JS3": "Suzuki", "JT1": "Toyota",
    "JT2": "Toyota", "JT3": "Toyota", "JT4": "Toyota",
    "JTD": "Toyota", "JTH": "Lexus", "JTJ": "Lexus",
    "JYA": "Yamaha", "KLA": "Daewoo", "KM1": "Hyosung (motorcycles)",
    "KMH": "Hyundai", "KMT": "Genesis", "KMY": "Daelim (motorcycles)",
    "KNA": "Kia", "KND": "Kia", "KNM": "Renault Korea",
    "KPA": "SsangYong", "KPT": "SsangYong", "L1N": "XPeng",
    "L4B": "Xingyue Group (motorcycles)", "L5C": "KangDi (ATV)", "L5K": "Zhejiang Yongkang Easy Vehicle",
    "L5N": "Zhejiang Taotao, China (ATV & motorcycles)", "L5Y": "Merato Motorcycle Taizhou Zhongneng", "L6T": "Lynk & Co",
    "L85": "Zhejiang Yongkang Huabao Electric Appliance", "L8X": "Zhejiang Summit Huawin Motorcycle", "LAE": "Jinan Qingqi Motorcycle",
    "LAL": "Sundiro Honda Motorcycle", "LAN": "Changzhou Yamasaki Motorcycle", "LB2": "Geely Motorcycles",
    "LBB": "Zhejiang Qianjiang Motorcycle (Keeway/Generic)", "LBE": "Beijing Hyundai", "LBM": "Zongshen Piaggio",
    "LBP": "Chongqing Jainshe Yamaha (motorcycles)", "LBV": "BMW Brilliance", "LCE": "Hangzhou Chunfeng Motorcycles (CFMOTO)",
    "LDC": "Dong Feng Peugeot Citroen (DPCA), China", "LDD": "Dandong Huanghai Automobile", "LDF": "Dezhou Fulu Vehicle (motorcycles)",
    "LDN": "SouEast Motor", "LDY": "Zhongtong Coach, China", "LE4": "Beijing Benz, China",
    "LET": "Jiangling-Isuzu Motors, China", "LFB": "FAW Bestune", "LFG": "Taizhou Chuanl Motorcycle Manufacturing",
    "LFP": "FAW, China (passenger vehicles)", "LFT": "FAW, China (trailers)", "LFV": "FAW-Volkswagen",
    "LFW": "FAW JieFang, China", "LFY": "Changshu Light Motorcycle Factory", "LGB": "Dong Feng (DFM), China",
    "LGH": "Qoros (formerly Dong Feng (DFM)), China", "LGW": "Great Wall", "LGX": "BYD Auto, China",
    "LH1": "FAW-Haima, China", "LHB": "Beijing Automotive Industry Holding", "LJ1": "JAC, China",
    "LJC": "JAC, China", "LJD": "Yueda Kia", "LKL": "Suzhou King Long, China",
    "LL6": "Hunan Changfeng Manufacture Joint-Stock", "LL8": "Linhai (ATV)", "LMC": "Suzuki Hong Kong (motorcycles)",
    "LMG": "GAC Trumpchi", "LPR": "Yamaha Hong Kong (motorcycles)", "LPS": "Polestar (Volvo) (Sweden)",
    "LRW": "Tesla", "LSG": "SAIC-GM", "LSJ": "MG / Roewe",
    "LSV": "SAIC Volkswagen", "LSY": "Brilliance Zhonghua", "LTP": "National Electric Vehicle Sweden AB (NEVS)",
    "LTV": "Toyota Tian Jin", "LUC": "Honda", "LV3": "National Electric Vehicle Sweden AB (NEVS)",
    "LVG": "GAC Toyota", "LVH": "Dongfeng Honda", "LVR": "Changan Mazda",
    "LVS": "Changan Ford", "LVV": "Chery, China", "LVZ": "Dong Feng Sokon Motor Company (DFSK)",
    "LW4": "Li Auto", "LYV": "Volvo", "LZE": "Isuzu Guangzhou, China",
    "LZG": "Shaanxi Automobile Group, China", "LZM": "MAN China", "LZP": "Zhongshan Guochi Motorcycle (Baotian)",
    "LZY": "Yutong Zhengzhou, China", "LZZ": "Sinotruk Howo", "MA1": "Mahindra",
    "MA3": "Maruti Suzuki", "MA6": "GM India", "MA7": "Mitsubishi India (formerly Honda)",
    "MAB": "Mahindra", "MAC": "Mahindra & Mahindra", "MAJ": "Ford",
    "MAK": "Honda", "MAL": "Hyundai", "MAT": "Tata",
    "MB1": "Ashok Leyland", "MB8": "Suzuki India Motorcycles", "MBF": "Royal Enfield",
    "MBH": "Suzuki India (Maruti)", "MBJ": "Toyota India", "MBL": "Hero MotoCorp",
    "MBR": "Mercedes-Benz India", "MC2": "Volvo Eicher commercial vehicles limited.", "MCA": "Fiat India",
    "MCB": "GM India", "MD2": "Bajaj", "MD6": "TVS",
    "MD9": "Shuttle Cars India", "MDH": "Nissan India", "MEC": "Daimler India Commercial Vehicles",
    "MEE": "Renault India", "MEX": "Škoda", "MHF": "Toyota Indonesia",
    "MHR": "Honda Indonesia", "MLC": "Suzuki Thailand", "MLH": "Honda Thailand",
    "MM8": "Mazda Thailand", "MMA": "Mitsubishi Thailand", "MMB": "Mitsubishi Thailand",
    "MMC": "Mitsubishi Thailand", "MML": "MG Thailand (SAIC)", "MMM": "Chevrolet Thailand",
    "MMS": "Suzuki Thailand", "MMT": "Mitsubishi Thailand", "MMU": "Holden Thailand",
    "MNB": "Ford Thailand", "MNT": "Nissan Thailand", "MP1": "Isuzu Thailand",
    "MPA": "Isuzu Thailand", "MR0": "Toyota Thailand", "MRH": "Honda Thailand",
    "MS0": "SSS MOTORS Myanmar", "MS3": "Suzuki Myanmar Motor Co.,Ltd.", "MZ7": "MG",
    "NAA": "Iran Khodro (Peugeot Iran)", "NAP": "Pars Khodro", "NC9": "VIRA Diesel",
    "NLA": "Honda Türkiye", "NLE": "Mercedes-Benz Türk Truck", "NLH": "Hyundai Assan",
    "NLN": "Karsan", "NLR": "OTOKAR", "NLT": "TEMSA",
    "NM0": "Ford Turkey", "NM4": "Tofaş Türk", "NMB": "Mercedes-Benz Türk Buses",
    "NMC": "BMC", "NMT": "Toyota Türkiye", "NNA": "Isuzu Turkey",
    "NP9": "Bozankaya", "PE1": "Ford Philippines", "PE3": "Mazda Philippines",
    "PL1": "Proton, Malaysia", "PNA": "NAZA, Malaysia (Peugeot)", "R2P": "Evoke Electric Motorcycles HK",
    "RA1": "Steyr Trucks International FZE, UAE", "RF3": "Aeon Motor, Taiwan", "RFB": "Kymco, Taiwan",
    "RFG": "Sanyang SYM, Taiwan", "RFL": "Adly, Taiwan", "RFT": "CPI, Taiwan",
    "SA9": "OX Global", "SAB": "Optare", "SAD": "Jaguar",
    "SAJ": "Jaguar", "SAL": "Land Rover", "SAR": "Rover",
    "SAX": "Austin-Rover", "SB1": "Toyota UK", "SBM": "McLaren",
    "SCA": "Rolls-Royce", "SCB": "Bentley", "SCC": "Lotus",
    "SCE": "DeLorean Motor Cars N. Ireland (UK)", "SCF": "Aston Martin", "SCK": "iFor Williams",
    "SDB": "Peugeot UK (formerly Talbot)", "SDP": "MG", "SED": "General Motors Luton Plant",
    "SEY": "LDV", "SFA": "Ford", "SFD": "Alexander Dennis UK",
    "SFZ": "Tesla (Lotus)", "SHH": "Honda", "SHS": "Honda",
    "SJA": "Bentley", "SJN": "Nissan", "SKA": "Vauxhall",
    "SKF": "Vauxhall", "SLA": "Rolls-Royce", "SLP": "JCB Research UK",
    "SMT": "Triumph", "SU9": "Solaris Bus & Coach (Poland)", "SUF": "Fiat Auto Poland",
    "SUL": "FSC (Poland)", "SUP": "FSO-Daewoo (Poland)", "SUU": "Solaris Bus & Coach (Poland)",
    "SWV": "TA-NO (Poland)", "TCC": "Micro Compact Car AG (smart 1998-1999)", "TDM": "QUANTYA Swiss Electric Movement (Switzerland)",
    "TK9": "SOR buses (Czech Republic)", "TM9": "Škoda trolleybuses (Czech Republic)", "TMA": "Hyundai Motor Manufacturing Czech",
    "TMB": "Škoda", "TMK": "Karosa (Czech Republic)", "TMP": "Škoda trolleybuses (Czech Republic)",
    "TMT": "Tatra (Czech Republic)", "TN9": "Karosa (Czech Republic)", "TNE": "TAZ",
    "TRA": "Ikarus Bus", "TRU": "Audi", "TSB": "Ikarus Bus",
    "TSE": "Ikarus Egyedi Autobuszgyar, (Hungary)", "TSM": "Suzuki Hungary", "TW1": "Toyota Caetano Portugal",
    "TYA": "Mitsubishi Trucks Portugal", "TYB": "Mitsubishi Trucks Portugal", "U5Y": "Kia Motors Slovakia",
    "U6Y": "Kia Motors Slovakia", "UU1": "Renault Dacia, (Romania)", "UU2": "Oltcit",
    "UU3": "ARO", "UU4": "Roman SA", "UU5": "Rocar",
    "UU6": "Daewoo Romania", "UU7": "Euro Bus Diamond", "UU9": "Astra Bus",
    "UV9": "ATP Bus", "UWR": "Robus Reșița", "UZT": "UTB (Uzina de Tractoare Brașov)",
    "VAG": "Magna Steyr Puch", "VAN": "MAN Austria", "VBK": "KTM",
    "VF1": "Renault", "VF2": "Renault Trucks", "VF3": "Peugeot",
    "VF4": "Talbot", "VF6": "Renault Trucks", "VF7": "Citroën",
    "VF8": "Matra", "VF9": "Bugatti", "VFA": "Alpine",
    "VG5": "MBK (motorcycles)", "VLU": "Scania", "VN1": "Renault",
    "VNE": "Irisbus (France)", "VNK": "Toyota", "VNV": "Nissan",
    "VR1": "DS Automobiles", "VR3": "Peugeot", "VR7": "Citroën",
    "VS6": "Ford", "VS7": "Citroën", "VS8": "Peugeot",
    "VS9": "Carrocerias Ayats (Spain)", "VSA": "Mercedes-Benz", "VSE": "Santana",
    "VSK": "Nissan", "VSS": "SEAT", "VSX": "Opel",
    "VTH": "Derbi (motorcycles)", "VTL": "Yamaha Spain (motorcycles)", "VTT": "Suzuki Spain (motorcycles)",
    "VV9": "TAURO Spain", "VWA": "Nissan Spain", "VWV": "Volkswagen",
    "VX1": "Zastava / Yugo Serbia", "VXE": "Opel", "VXK": "Opel",
    "W09": "RUF", "W0L": "Opel", "W0V": "Opel",
    "W1A": "smart", "W1K": "Mercedes-Benz", "W1N": "Mercedes-Benz",
    "W1V": "Mercedes-Benz", "WA1": "Audi", "WAG": "Neoplan",
    "WAU": "Audi", "WB1": "BMW Motorrad", "WB5": "BMW",
    "WBA": "BMW", "WBS": "BMW M", "WBW": "BMW",
    "WBX": "BMW", "WBY": "BMW i", "WDA": "Daimler",
    "WDB": "Mercedes-Benz", "WDC": "Mercedes-Benz", "WDD": "Mercedes-Benz",
    "WDF": "Mercedes-Benz", "WEB": "Mercedes-Benz (EvoBus)", "WEL": "e.GO Mobile",
    "WF0": "Ford", "WF1": "Ford", "WJM": "Iveco Magirus",
    "WKE": "Fahrzeugwerk Bernard Krone (truck trailers)", "WKK": "Setra", "WMA": "MAN",
    "WME": "smart", "WMW": "MINI", "WMX": "Mercedes-AMG",
    "WMZ": "MINI", "WNA": "Next.e.GO", "WP0": "Porsche",
    "WP1": "Porsche", "WS5": "StreetScooter", "WS7": "Sono Motors",
    "WSM": "Schmitz-Cargobull (truck trailers)", "WUA": "Audi Sport", "WV1": "Volkswagen Commercial",
    "WV2": "Volkswagen Commercial", "WV3": "Volkswagen Commercial", "WVE": "Volkswagen Commercial",
    "WVG": "Volkswagen", "WVW": "Volkswagen", "X1M": "PAZ (Russia)",
    "X4X": "AvtoTor (Russia, BMW SKD)", "X7L": "Renault AvtoFramos (Russia)", "X7M": "Hyundai TagAZ (Russia)",
    "XL4": "Lightyear", "XL9": "Spyker", "XLB": "Volvo (NedCar)",
    "XLE": "Scania Netherlands", "XLR": "DAF (trucks)", "XMC": "Mitsubishi (NedCar)",
    "XMG": "VDL Bus & Coach", "XP7": "Tesla, Inc. (Gigafactory Berlin-Brandenburg)", "XTA": "Lada",
    "XTC": "KamAZ", "XTH": "GAZ", "XTT": "UAZ",
    "XTU": "Trolza (Russia)", "XTY": "LiAZ (Russia)", "XUF": "General Motors Russia",
    "XUU": "AvtoTor (Russia, General Motors SKD)", "XW8": "Volkswagen Group Russia", "XWB": "UZ-Daewoo (Uzbekistan)",
    "XWE": "AvtoTor (Russia, Hyundai-Kia SKD)", "Y3M": "MAZ (Belarus)", "Y4K": "Geely (Belarus)",
    "Y6D": "Zaporozhets/AvtoZAZ (Ukraine)", "YB1": "Volvo Trucks Belgium", "YBW": "Volkswagen Belgium",
    "YCM": "Mazda Belgium", "YE2": "Van Hool (buses)", "YH2": "BRP Finland (Lynx snowmobiles)",
    "YK1": "Saab-Valmet Finland", "YS2": "Scania", "YS3": "Saab",
    "YS4": "Scania Bus", "YSC": "Cadillac (Saab)", "YSR": "Polestar",
    "YT9": "Koenigsegg / Carvia", "YTN": "Saab (NEVS)", "YU7": "Husaberg (motorcycles)",
    "YV1": "Volvo", "YV2": "Volvo Trucks", "YV3": "Volvo Buses",
    "YV4": "Volvo", "YVV": "Polestar (Volvo) (Sweden)", "Z8M": "Marussia (Russia)",
    "ZAA": "Alfa Romeo", "ZAM": "Maserati", "ZAP": "Piaggio/Vespa/Gilera",
    "ZAR": "Alfa Romeo", "ZBN": "Benelli", "ZCF": "Iveco",
    "ZCG": "Cagiva SpA / MV Agusta", "ZD0": "Yamaha", "ZD3": "Beta",
    "ZD4": "Aprilia", "ZDC": "Honda Italia Industriale SpA", "ZDF": "Ferrari Dino",
    "ZDM": "Ducati", "ZFA": "Fiat", "ZFB": "Fiat",
    "ZFC": "Fiat", "ZFF": "Ferrari", "ZFR": "Pininfarina",
    "ZGA": "Iveco", "ZGU": "Moto Guzzi", "ZHU": "Husqvarna",
    "ZHW": "Lamborghini", "ZJM": "Malaguti", "ZJN": "Innocenti",
    "ZKH": "Husqvarna Motorcycles Italy", "ZLA": "Lancia", "ZN6": "Maserati",
    "ZPB": "Lamborghini",
    // 2-character WMI prefixes (small-volume manufacturers)
    "1G": "General Motors USA", "1H": "Honda USA", "1L": "Lincoln USA",
    "1N": "Nissan USA", "2M": "Mercury", "2T": "Toyota Canada",
    "3G": "General Motors Mexico", "3H": "Honda Mexico", "3N": "Nissan Mexico",
    "4F": "Mazda USA", "4M": "Mercury", "4S": "Subaru-Isuzu Automotive",
    "4T": "Toyota", "5F": "Honda USA-Alabama", "5J": "Honda USA-Ohio",
    "5L": "Lincoln", "5T": "Toyota USA - trucks", "JA": "Isuzu",
    "JD": "Daihatsu", "JF": "Fuji Heavy Industries (Subaru)", "JK": "Kawasaki (motorcycles)",
    "JN": "Nissan", "JS": "Suzuki", "JT": "Toyota",
    "JY": "Yamaha (motorcycles)", "KL": "Daewoo General Motors South Korea", "KM": "Hyundai",
    "KN": "Kia",
]
